const gulp = require('gulp');
const plumber = require('gulp-plumber');
const htmlmin = require('gulp-htmlmin');
const cleancss = require('gulp-clean-css');
const gzip = require('gulp-gzip');
const del = require('del');
const useref = require('gulp-useref');
const gulpif = require('gulp-if');

gulp.task('clean', function () {
    return del(['data/*']);
});

gulp.task('www', function () {
    return gulp.src('www/**')
        .pipe(plumber())
        .pipe(gulpif('*.html', htmlmin({
            "caseSensitive": false,
            "collapseBooleanAttributes": true,
            "collapseInlineTagWhitespace": false,
            "collapseWhitespace": true,
            "conservativeCollapse": false,
            "decodeEntities": true,
            "html5": true,
            "includeAutoGeneratedTags": false,
            "keepClosingSlash": false,
            "maxLineLength": 0,
            "minifyCSS": true,
            "minifyJS": true,
            "preserveLineBreaks": false,
            "preventAttributesEscaping": false,
            "processConditionalComments": true,
            "processScripts": [
                "text/html"
            ],
            "removeAttributeQuotes": true,
            "removeComments": true,
            "removeEmptyAttributes": true,
            "removeEmptyElements": false,
            "removeOptionalTags": true,
            "removeRedundantAttributes": true,
            "removeScriptTypeAttributes": true,
            "removeStyleLinkTypeAttributes": true,
            "removeTagWhitespace": true,
            "sortAttributes": true,
            "sortClassName": true,
            "trimCustomFragments": true,
            "useShortDoctype": true
        })))
        .pipe(gulpif('*.css', cleancss()))
        .pipe(gulpif("!*.json", gzip()))
        .pipe(gulp.dest('data'));
});

gulp.task('buildfs', gulp.series('clean', 'www'));
gulp.task('default', gulp.series('buildfs'));